### ISSUE TITLE
Same device: Log in with another account. The details of previously logged account also keep appearing. (See details)

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#107]
**Issue:**  
- Device is logged in with an account user 'meero' which has a profile picture and a bank card.
- Log out.
- Log in with an account user with default profile picture and no cards added.

**What is happening:**
- The new account 'khan' didn't upload any profile picture but it shows the profile picture of previously logged in account id 'meero'

- The new account 'khan' didn't add any bank cards but it shows card of previously logged in account id 'meero', which is overlapping with text.

![cats](https://user-images.githubusercontent.com/53593496/64017410-fe863880-cb42-11e9-8d60-661130c813d7.jpg)

**Comment by UsmanTahir101** [comment]
Done

**Comment by isabeen** [comment]
@UsmanTahir101  same issue is occuring

**Comment by UsmanTahir101** [comment]
Done

**Comment by isabeen** [comment]
@UsmanTahir101  issue still occuring on the 'Manage Payment' screen (Deposit Details tab)

**Comment by UsmanTahir101** [comment]
Done
